// gossip/components/login-form.tsx
"use client";

import { Button } from "@/components/ui/button";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { getSerializedIdentityKeys } from "@/lib/local-stores";
import { cn } from "@/lib/utils";
import { ErrorResponse } from "@/types";
import { useState } from "react";

export function LoginForm({
  className,
  ...props
}: React.ComponentProps<"div">) {
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [sent, setSent] = useState(false);

  const sendMagicLink = async (e: React.SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);

    const keys = await getSerializedIdentityKeys();
    const res = await fetch(
      process.env.NEXT_PUBLIC_API_URL + "auth/send-magic-link",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
        body: JSON.stringify({ email, pubkey: keys.pubKey }),
      },
    );

    const data = await res.json();

    if (!res.ok) {
      //TODO: error handling
      throw {
        code: data.code,
        message: data.message,
        details: data.details,
      } satisfies ErrorResponse;
    }
    setSent(true);
    setLoading(false);
  };
  return (
    <div className={cn("flex flex-col gap-6", className)} {...props}>
      {sent && <span>Magic link sent to your email.</span>}
      <form onSubmit={sendMagicLink}>
        <FieldGroup>
          <Field>
            <FieldLabel htmlFor="email">Email</FieldLabel>
            <Input
              id="email"
              type="email"
              onChange={(e) => setEmail(e.target.value)}
              placeholder="m@example.com"
              required
            />
          </Field>
          <Field>
            <Button type="submit" disabled={loading}>
              Login
            </Button>
          </Field>
        </FieldGroup>
      </form>
    </div>
  );
}

// gossip/src/components/LoginForm.vue
<script setup lang="ts">
import { ref, type HTMLAttributes } from "vue";

import { Button } from "@/components/ui/button";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { getSerializedIdentityKeys } from "@/lib/local-stores";
import { cn } from "@/lib/utils";
import { useSendMagicLink } from "@/composables/auth";

const props = defineProps<{
    class?: HTMLAttributes["class"];
}>();

const email = ref("");
const { error, success, asyncStatus, sendMagicLink } = useSendMagicLink();

const sendLink = async (e: any) => {
    e.preventDefault();

    const identityKeyPair = await getSerializedIdentityKeys();
    await sendMagicLink({ email: email.value, pubkey: identityKeyPair.pubKey });
};
</script>

<template>
    <div :class="cn('flex flex-col gap-6', props.class)">
        <div v-if="error">
            <p>{{ error.message }}</p>
        </div>
        <div v-if="success">
            <p>Check your email for the login link.</p>
        </div>
        <form v-else @submit="sendLink">
            <FieldGroup>
                <!--<!-- App Name -->
                <!-- <h1 class="text-xl font-bold text-center">Chitchat</h1> -->

                <Field>
                    <FieldLabel for="email"> Email </FieldLabel>
                    <Input
                        id="email"
                        type="email"
                        v-model="email"
                        placeholder="m@example.com"
                        required
                    />
                </Field>

                <Field>
                    <Button type="submit" :disabled="asyncStatus === 'loading'">
                        Login
                    </Button>
                    <span class="text-gray-500">We'll send you login link</span>
                </Field>
            </FieldGroup>
        </form>
    </div>
</template>
